services:
  - type: web
    name: altprivat-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4